### ISSUE TITLE
You don't have or can't use skill #7297, macro aborted. - but skill was already used

### ISSUE THREAD

**Issue by Crotha** [C2Talon/c2t_hccs#1]
Running c2t_hccs worked quite well by now, but currently running into the following problem:

>[64] The Neverending Party
>Encounter: party girl
>Round 0: Dysis wins initiative!
>Round 1: Dysis executes a macro!
>Round 1: Dysis casts SING ALONG!
>Round 2: Dysis executes a macro!
>KoLmafia thinks it is round 3 but KoL thinks it is round 2
>You're on your own, partner. (You don't have or can't use skill #7297, macro aborted.)
>Click here to continue in the relay browser.

Skill 7297 is "Sing along", which was already used, but seemingly the combat script tries to use it again.
It only just now started, I think the script tries to get punching potion and uses meat-sing-a-long on the way?

Just so you know. Thanks a lot!

**Comment by C2Talon** [comment]
If you include part of the log that also include the previous 2 or so combats as well, I'd have a better idea where in the script this is happening.

There's a few guesses as to the why:
- It's reentering the combat script too quickly after submitting the first macro
- There's a missing requirement or a lapse in logic somewhere

I don't know if the first one is actually a thing, but I did push an attempted fix yesterday based on the very rare instances of something similar happening to me.

As for the second guess, it could be something I didn't think of to explicitly list as a requirement, or just a flub, which seeing the things leading up to it would help pinpoint.

**Comment by Crotha** [comment]
Edit: added as text-file

Seemingly my problem is, it wasn't recording the error messages or anything?
Everytime it says "c2t_hccs took [...]" the script broke. 
Never really looked at them before, are there better logfiles / debugging possibilites anywhere?
Sorry 
[session_file.txt](https://github.com/C2Talon/c2t_hccs/files/7382181/session_file.txt)
:/

**Comment by C2Talon** [comment]
It looks like it's not properly detecting the number of remaining free kills, since it really should not be adventuring in NEP after free kills are spent. And that's why it's not using a skill after the sing along: because there just isn't a free kill left to use.

If you could run this on the CLI at some point and paste the result here, it might give me some insight as to what is going on:
```ash import <c2t_hccs.ash> print(`{c2t_hccs_freeKillsLeft()};{available_amount($item[lil' doctor&trade; bag])},{get_property("_chestXRayUsed")};{have_skill($skill[shattering punch])},{get_property("_shatteringPunchUsed")};{have_skill($skill[gingerbread mob hit])},{get_property("_gingerbreadMobHitUsed")}`);```

**Comment by Crotha** [comment]
I am sorry, I seem to have missed the notification eMail.
Obviously the situation is completely different now - I can try again probably after Halloween earliest.

But something else happened the last days: both during two garbo-runs as well as today's autoscend, the "Shocking Lick"-prefref wasn't cleared. I had to set the prefref manually to the correct value.   

Maybe the same thing happened here too - then it wouldn't have been a problem of the script but of the prefref-clearing, which should be handled by mafia itself.   
I will update again next time running, but it looks as if the problem wasn't on the script's side.

**Comment by C2Talon** [comment]
This script doesn't actually try to use shocking lick, as it tries to not use batteries if it doesn't have to. And it'll only use batteries for the item test if it's needed, which is after leveling. Though it'll let you know if there is a shocking lick charge available when the script ends.

The CLI bit is just to see if mafia is detecting the other free kills them as I expect, as I know you don't have some of the free kills I do which are used in the script. I've actually had few problems in dealing with gingerbread mob hit in particular, and just want to make sure it's detecting when someone doesn't have it properly.

Though I suspect it may have been because you were using an older version of the script, which the CLI bit will also weed out as `c2t_hccs_freeKillsLeft()` was something I added more recently to more nicely deal with free kills. If the CLI bit errors out, you'd just need to delete and reinstall the script. Sometimes the SVN implementation on mafia bugs out with git repositories and doesn't actually update things when it says it's updating.
